### ISSUE TITLE
error con los nodos pub/sub

### ISSUE THREAD

**Issue by elopezmadrid** [jorgeeecm/node-red-contrib-iot-in-gcp#3]
No consigo hacer funcionar los nodos pub/sub, el apartado key de credentials que formato tiene que tener, tengo el json generado por google que me funciona con otros nodos, pero con este no me funciona

**Comment by jorgeeecm** [comment]
> No consigo hacer funcionar los nodos pub/sub, el apartado key de credentials que formato tiene que tener, tengo el json generado por google que me funciona con otros nodos, pero con este no me funciona

Buenas, el formato efectivamente es el json generado en Google. Si te funciona en los demás nodos quizás el problema esté en la subscripción o el topic que estés especificando, si puedes hacer una comprobación para descartar esta posibilidad. 

Otra opción es que hayan cambiado algo de la API y se hayan quedado anticuados.

**Comment by jorgeeecm** [comment]
Closing the issue as there are no response from the user.
