### ISSUE TITLE
ReferenceError: STATUS_PUBLISHING is not defined pubsub.js

### ISSUE THREAD

**Issue by alexszilagyi** [jorgeeecm/node-red-contrib-iot-in-gcp#8]
I am using the following versions:

**node-red-contrib-iot-in-gcp, version: 0.1.1**

```
[info] Node-RED version: v1.3.5
[info] Node.js  version: v16.3.0
[info] Darwin 20.6.0 x64 LE
[info] Loading palette nodes
[info] Dashboard version 2.30.0 started at /ui
```

When starting node-red I get the following errors, and the bug relies [on this line of file pubsub.js](https://github.com/jorgeeecm/node-red-contrib-iot-in-gcp/blob/master/pubsub.js#L160):

Prompted error:

<img width="1256" alt="Screenshot 2022-02-02 at 23 37 34" src="https://user-images.githubusercontent.com/1736655/152249371-9993689b-bb4a-4c49-a0ba-2700676fc866.png">

Error line
<img width="1217" alt="Screenshot 2022-02-02 at 23 39 55" src="https://user-images.githubusercontent.com/1736655/152249358-00114ea4-e7f1-46da-abb0-04d3e76dce79.png">

**Comment by jorgeeecm** [comment]
Notice that the code is discontinued since 2020, it is possible that the API got updated and this state is no more supported, one quick "Work Around" could be comment this line. The propper one is checking the API and see what is the used status and change it in the code.

Please feel free to modify any issue you found and open a Pull Request.

**Comment by alexszilagyi** [comment]
Hi @jorgeeecm ,

Thanks for the prompt reply! Where I should check the API? On node-red docs?

Can you paste some references (links for docs) ?

I'd more than happy to help and contribute to this repo with a PR afterwards.

**Comment by jorgeeecm** [comment]
I have reviewed the code and it is a missing definition, you just need to define it in the file like the rest:

` const STATUS_PUBLISHING = {
        fill:  "blue",
        shape: "dot",
        text:  "publishing"
    }; `

When I have time I can me the changes and upgrade the code, or you can create the branch and open the Pull Request (up to you). 

Thanks for reporting the bug.
